[project]
name = "ex1"
version = "0.1.0"
description = "matrix data analysis"
authors = [
    {name = "sgergero"}
]
requires-python = ">=3.12"
dependencies = [
    "pandas (>=3.0.6,<4.0.0)",
    "numpy (>=2.5.3,<3.0.0)",
    "requests (>=2.34.2,<3.0.0)",
    "matplotlib (>=3.11.2,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
